extension on SubErrorCode{
  bool equals(String e) => this.typeToString() == e;

  String typeToString() => this.toString().split(".").last;
}
enum SubErrorCode{
  INVALID_BODY,
  PERMISSION_DENIED,
  PARAM_NOT_FOUND,
  INVALID_TOKEN,
  INVALID_FIELD_VALUE,
  INTEGRATION_NOT_ENABLED,
  INVALID_SPLIT_PERCENTAGE,
  INVALID_PHONE,
  INVALID_PROVIDER,
  PAST_DUE_DATE,
  CANNOT_EXECUTE_WHILE_PROCESSING,
  INVALID_PASSWORD,
  ACCOUNT_ALREADY_HAS_LOGIN,
  INVALID_LOGIN_OR_PASSWORD,
  LOGIN_NOT_FOUND,
  ACCOUNT_CANT_HAVE_BALANCE,
  ALREADY_EXISTS,
  INVALID_CPF,
  INVALID_EMAIL,
  FIELDS_WITH_INVALID_VALUE,
  MISSING_KYC
}